### ISSUE TITLE
木の斧を持ちながら感圧版を踏んだ際

### ISSUE THREAD

**Issue by gamesukimanIRS** [itsu020402/WorldEditorEX#1]
このWorldEditを使用させて頂いています。

少し気になったのですが、木の斧を持ちながら感圧版を踏むと、タップ(右クリ)した時と同じことが起き、踏んでる間ずっと地点2を設置しましたのメッセージが出続けます。

こちらのバグは修正することは不可能でしょうか？

使用しているものはNukkitです。Nukkitの仕様でしたら諦めます。

**Comment by itsu020402** [comment]
ご利用ありがとうございます。
当該バグについてはPlayerInteractEventによって処理を行っているためだと思われます。
仕様が変わってしまった可能性があるため、代替イベントを確認次第修正したいと思います。
ご報告ありがとうございました。
